/*
 * STEPPER_prg.c
 *
 *  Created on: Jul 23, 2025
 *      Author: pc
 */
#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"
#include <util/delay.h>
#include "../../MCAL/DIO/DIO_int.h"

#include "STEPPER_int.h"

void STEPPER_vInit(void)
{
	MDIO_vSetPinDir(STEPPET_PORT, STEPPER_BLUE_T, DIO_OUTPUT);
	MDIO_vSetPinDir(STEPPET_PORT, STEPPER_PINK_T, DIO_OUTPUT);
	MDIO_vSetPinDir(STEPPET_PORT, STEPPER_YELLOW_T, DIO_OUTPUT);
	MDIO_vSetPinDir(STEPPET_PORT, STEPPER_ORANGE_T, DIO_OUTPUT);
}
void STEPPER_vRotateCW(f64 A_f64Speed) /* TODO : angle */
{
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_HIGH);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_HIGH);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_HIGH);
	_delay_ms(A_f64Speed);
}
void STEPPER_vRotateCCW(f64 A_f64Speed) /* TODO : angle */
{
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_HIGH);
	_delay_ms(A_f64Speed);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_HIGH);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_HIGH);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);
	_delay_ms(A_f64Speed);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_HIGH);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);

}
void STEPPER_vStop(void)
{
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_BLUE_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_PINK_T,   DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_YELLOW_T, DIO_LOW);
	MDIO_vSetPinVal(STEPPET_PORT, STEPPER_ORANGE_T, DIO_LOW);
}
